MarketPlace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path("",include('core.urls')),
    path('dashboard',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path("admin/", admin.site.urls),
    path("items/", include('items.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import contact,index,signup
from .forms import LoginForm
app_name='core'
urlpatterns = [
    path("",index,name='index'),
    path("contact/",contact,name='contact'),
    path("signup/",signup,name="signup"),
    path("login/",auth_views.LoginView.as_view(template_name='login.html',authentication_form=LoginForm),name='login'),
]

items/urls.py
from django.urls import path
from . import views
app_name='apps'
urlpatterns=[
    path("<int:pk>/",views.detail,name='detail'),
    path('new/',views.new,name='new'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('',views.items,name='items'),
]

items/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=120)
    class Meta:
        ordering=('name',)
        verbose_name_plural='Categories'
    def __str__(self):
        return self.name


class Item(models.Model):
    class Meta:
        verbose_name_plural='Items'
    category=models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    Name=models.CharField(max_length=120,null=False)
    Description=models.TextField(null=False)
    price=models.FloatField(default=0,null=False)
    is_sold=models.BooleanField(default=False)
    created_at=models.DateField(auto_now_add=True)
    created_by=models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    image=models.ImageField(upload_to='item_images',blank=True,null=True)

    def __str__(self):
        return self.Name

items/forms.py
from django import forms
from .models import Item
input_class='w-full py-4 py-6 rounded-xl border'
class NewItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=('category','Name','Description','price','image')
        widgets={
            'category':forms.Select(attrs={
                'class':'w-full py-4 py-6 rounded-xl border'
            }),
            'Name':forms.TextInput(attrs={
                'class':input_class
            }),
            'Description':forms.TextInput(attrs=
                                          {
                                              'class':input_class
                                          }),
            'price':forms.TextInput(attrs={
                'class':input_class
            }),
            'image':forms.FileInput(attrs={
                'class':input_class
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=('category','Name','Description','price','image','is_sold')
        widgets={
            'category': forms.Select(attrs={
                'class': 'w-full py-4 py-6 rounded-xl border'
            }),
            'Name':forms.TextInput(attrs={
                'class':input_class
            }),
            'Description':forms.TextInput(attrs=
                                          {
                                              'class':input_class
                                          }),
            'price':forms.TextInput(attrs={
                'class':input_class
            }),
            'image':forms.FileInput(attrs={
                'class':input_class
            })
        }

items/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Item,Category
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm,EditItemForm
# Create your views here.

def items(request):
    query=request.GET.get('query','')
    category_id=request.GET.get('category',0)
    category=Category.objects.all()
    items=Item.objects.filter(is_sold=False)
    if category_id:
        items=items.filter(category_id=category_id)
    if query:
        items=items.filter(Q(Name__icontains=query)| Q(Description__icontains=query)|Q(category__name__icontains=query))
    return render(request,'items.html',{
        'items':items,
        'query':query,
        'categories':category,
        'category_id':int(category_id)
    })


def detail(request,pk):
    item=get_object_or_404(Item,pk=pk)
    related_items=Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[0:3]
    return render(request,'item_detail.html',{'item':item,'related_item':related_items})

@login_required
def new(request):
    if request.method=="POST":
        form=NewItemForm(request.POST,request.FILES)
        if form.is_valid():
            item=form.save(commit=False)
            item.created_by=request.user
            item.save()
            return redirect('apps:detail',pk=item.id)
    else:
        form=NewItemForm()
    return render(request,'form.html',{'form':form,
                                       'title':'New item'})
@login_required
def delete(request,pk):
    item=get_object_or_404(Item,pk=pk)
    item.delete()
    return redirect("dashboard:index")

@login_required
def edit(request,pk):
    item = get_object_or_404(Item, pk=pk)
    if request.method=="POST":
        form=EditItemForm(request.POST,request.FILES,instance=item)
        if form.is_valid():
            form.save()
            return redirect('apps:detail',pk=item.id)
    else:
        form=EditItemForm(instance=item)
    return render(request,'form.html',{'form':form,
                                       'title':'Edit item'})

items/templates/form.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock%}}
{% block content%}
    <h1 class="mb-6 text-3xl">{{ title }}</h1>
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-4">
            {{ form.as_p }}
        </div>
    {% if form.errors or form.non_field_errors %}
            <div class="mb-6 p-6 bg-red-100 rounded-xl">
            <h1>
                {% for field in form %}
                    {{ field.errors}}
                {% endfor %}
            </h1>
            </div>
    {% endif %}
     <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
{% endblock %}

items/templates/item_detail.html
{% extends 'base.html'%}
{% block title %}
    {{ item.Name }}
{% endblock %}
{% block content %}
<div class="grid grid-cols-6 gap-6 bg-gray-100">
<div class="col-span-3">
    <img src="{{  item.image.url}}" class="rounded-xl">
</div>
<div class="col-span-3 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ item.Name }}</h1>
    <p class="text-gray-500 "><strong>Price {{ item.price }}</strong></p>
    <p class="text-gray-500 "><strong>Seller {{ item.created_by }}</strong></p>
    {% if item.Description%}
        <p class="text-gray-500">
            <strong class="text-gray-500">Description</strong><br>
            {{ item.Description }}
        </p>
    {% endif %}
    {% if request.user == item.created_by %}
<div class="mt-6 p-6 bg-white rounded-xl">
    <p>This is your item!</p>
        <a href="{% url 'apps:edit' item.id%}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>

    <a href="{% url 'apps:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
</div>
{% else %}
    <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Contact Seller</a>
{% endif %}
</div>
</div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Items</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in related_item %}
            <div>
                <a href="{% url 'apps:detail' item.id %}">

                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.Name}}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

items/templates/items.html
{% extends 'base.html' %}
{% block title %}Items{% endblock %}
{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4">
<div class="col-span-1 bg-gray-100">
    <form method="get" action="{% url "apps:items" %}">

        <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Search">
        <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
    </form>
    <hr class="my-6">
    <p class="font-semibold">Categories</p>
    <ul>
        {% for category in categories%}
        <li class="py-2 px-2 rounded-xl" {% if category.id == category_id %}bg-gray-200{% endif %}>
            <a href="{% url "apps:items"%}?query={{ query }}&category={{ category.id }}">{{ category.name }}
            </a>
        </li>
    {% endfor %}
    </ul>
    <hr class="my-6">
        <p class="font-semibold">Clear Filter</p>
    <ul>
        <li><a href="{% url "apps:items" %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear Filters</a>
    </ul>
</div>
<div class="col-span-3">
    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
            <div>
                <a href="{% url 'apps:detail' item.id %}">

                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.Name}}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}